# Linear algebra

In [2]:
import numpy as np

In [3]:
v = np.random.randint(10, size=(3,))
m = np.random.randint(10, size=(5, 3))

In [4]:
m

array([[6, 5, 0],
       [4, 6, 5],
       [1, 6, 1],
       [0, 5, 1],
       [7, 5, 8]])

In [5]:
v

array([8, 8, 6])

## Dot products, determinants, traces

Dot product is available through `np` itself (as it's very common). Note the ordering and dimensions:

In [6]:
np.dot(m, v)

array([ 88, 110,  62,  46, 144])

In [14]:
np.dot(m, v[:, np.newaxis])

array([[ 88],
       [110],
       [ 62],
       [ 46],
       [144]])

In [8]:
np.dot(v, m.T)

array([ 88, 110,  62,  46, 144])

Inverse matrix is straighforward (as almost any other LA operation):

In [9]:
s = np.random.randint(10, size=(3,3))
s_inv = np.linalg.inv(s)

In [10]:
s

array([[2, 1, 1],
       [5, 2, 4],
       [2, 2, 8]])

In [11]:
s_inv

array([[-0.8,  0.6, -0.2],
       [ 3.2, -1.4,  0.3],
       [-0.6,  0.2,  0.1]])

In [ ]:
s_inv.dtype

In [12]:
np.dot(s_inv, s)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16,  1.00000000e+00, -4.44089210e-16],
       [ 2.77555756e-17, -2.77555756e-17,  1.00000000e+00]])

Determinants and traces are available as well:

In [ ]:
np.linalg.det(s), np.linalg.det(s_inv)  # det(s) == 1 / det(s_inv), btw

In [13]:
np.trace(s), np.trace(s_inv)

(12, -2.1000000000000005)

## Eigenvalues, eigenvectors

Eigenvalue decomposition (and other decompositions as well) are available via `eig` and `eigh` functions:

In [ ]:
evals, evectors = np.linalg.eig(s)

In [ ]:
evals

In [ ]:
evectors

In [ ]:
np.allclose(evals.sum(), np.trace(s))  # some simple LA and correct way of comparing floating point numbers

Creating a diagonal matrix from a `1D` array:

In [ ]:
s_diagonal = np.diag(evals)

In [ ]:
s_diagonal

And now our matrix can be decomposed as:
    
$$
s = VEV^{-1}
$$

where $E$ is a diagonal matrix (with eigenvalues on main diagonal), and $V$ is a matrix where columns are eigenvectors.

In [ ]:
np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors)))

In [ ]:
s

In [ ]:
np.allclose(np.dot(evectors, np.dot(s_diagonal, np.linalg.inv(evectors))), s)